name: Releasy

on:
  push:
    branches:
      - main

jobs:
  releasy:
    name: Releasy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Run Local Action
        uses: ./
